### ISSUE TITLE
Scrum 4 report 

### ISSUE THREAD

**Issue by chohyeonkim** [thekimsplustwo/VanCityPropertyPulse#155]
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?
--INCLUDE YOUR CSID IN YOUR POST--
Other Notes:
These are individual, so you are tracking your OWN work and duties
Can use this as a resource when you’re writing about your project on your resume or LinkedIn -> look back and remember details about implementation
We are having this due AFTER each workshop so that you are better able to understand the technology you’re going to be using
The real effort comes from talking to your group and planning your next steps!
Keep it short, succinct, and summarize the key points

Total: ~5 sentences max!

See Grading Rubric here: https://blogs.ubc.ca/cpsc4552023s/assessment-rubrics/#sec-2

DUE: Sunday at 10PM PT (7/17)

**Comment by chohyeonkim** [comment]
csid : w7n0n

**Comment by jieunkxx** [comment]
csid: j4n4c
1. 
mostly backend and infra related work such as database setup, connecting backend to database and MLS API, building new APIs, and auth flow 

2. authentication issue due to the incompatibility of the auth library with Google oAuth2.0 and Passport. We delivered the auth logic by modifying the library itself in the past sprint. Still, for better maintenance, the library is going to be replaced, and new auth logic will be implemented in this sprint.     

3. adding feature flags for better testing/dev env, replacing the auth flow, deploying the app + CI/CD tests, and building new API flow for the stretch goals.

**Comment by czhaoca** [comment]
csid: s6v0b

1. I worked on MapBox API integration, compare page implementation and AI Chat Bot concept realization research.
2. I faced difficulty in inserting MapBox API into the detail page this sprint, need to fit the map into the designated spot/layout next sprint.
3. I will work on finishing up MapBox API and compare page implementation as priority. Then working on stretch goals and website deployment in the upcoming sprint.

**Comment by chris718** [comment]
csid: e3e4o

1. During the past two weeks, I worked on building compare page and provisioning MongoDB Schemas. 
2. Making the compare page more user-friendly and intuitive is one of the challenges I've faced during the past iteration. After deciding on the page's design, hooking up data is also a challenge for me. 
3. For the coming iteration, I will focus on implementing and completing the compare page. After this, I will contribute to the stretch goals and other tasks that require additional help.

**Comment by pukkuKim** [comment]
csid: b2j9q
1. Over the last sprint, I worked on implementing Google login, pagination, and enhancing the user profile page.
2. Google authorization via Passport sounded fairly easy, but it didn't work smoothly as I'd expected. The other member (Jieun) had to take over the task.
3. I'll be working on some login-related (small) tasks, once the implementation is solid. My first task is to work on the front-end side of our chat bot.
