### ISSUE TITLE
Scrum 5 Report

### ISSUE THREAD

**Issue by pukkuKim** [thekimsplustwo/VanCityPropertyPulse#233]
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?
--INCLUDE YOUR CSID IN YOUR POST--
Other Notes:
These are individual, so you are tracking your OWN work and duties
Can use this as a resource when you’re writing about your project on your resume or LinkedIn -> look back and remember details about implementation
We are having this due AFTER each workshop so that you are better able to understand the technology you’re going to be using
The real effort comes from talking to your group and planning your next steps!
Keep it short, succinct, and summarize the key points

Total: ~5 sentences max!

See Grading Rubric here: https://blogs.ubc.ca/cpsc4552023s/assessment-rubrics/#sec-2

DUE: Sunday at 10PM PT (7/30)

**Comment by chohyeonkim** [comment]
csid: w7n0n


1. Over the past two weeks, I have primarily taken on frontend tasks. I've made some improvements to URL bugs and search/filter options, and also added other features. On the detail pages, I've integrated features like map box, social SNS sharing, and displaying nearby home information. Furthermore, I have fixed minor bugs.

2. One challenge I've noticed is that several functionalities are not working properly after deployment. Currently, we are exploring alternative solutions. Additionally, I am considering what innovative features could be added before the showcase.

3. For the next iteration, I plan to overall improve the interface. I also consider adding additional information to the details. I plan to ensure that everything runs smoothly even after deployment by incorporating tests.

**Comment by pukkuKim** [comment]
csid: b2j9q
1. My main task for the past sprint was implementing the chat bot (e.g. dialogue flow, front-end, etc.). I also made some changes on the frontend side.
2. I had a bit of troubles fully understanding how the chat bot works, and I still haven't figured out some of the features I want.
3. I'll keep working on implementing the chat bot. In addition, I'll be fixing some frontend stuffs and testing some of the backend functions.

**Comment by chris718** [comment]
csid: e3e4o

1. During the past iteration, my main task was to improve the compare page. I added some functionality to the page so that users can compare the desired properties more easily.

2. It took me a while to implement the removal of selected properties from the liked property list. Additionally, deployment is the main challenge that our team is currently facing.

3. For the next two weeks, I'll continue to improve the pages and add some tests for the backend functions.

**Comment by czhaoca** [comment]
csid: s6v0b

1. During the past two weeks, I was mainly focused on compare page backend hook up implementation. Then helped on deployment to cloud services.
2. Deployement on Render is causing issues due to free tier limitation. MaBox is also a challenge due to compatibility issue.
3. For the next iteration, will work on stretch requirements, bug fixing and maintain deployment instance.

**Comment by jieunkxx** [comment]
csid: j4n4c

1. I mainly focused on deploying our application, tackling issues like CORS and Auth, and additionally, developing a comparison API, implementing walk score and virtual tours on the detail page, and resolving various bugs to enhance application performance.

2. Deployment posed significant challenges due to issues associated with CORS and authentication. Overcoming these problems necessitated in-depth problem-solving skills and a comprehensive understanding of extra network/security protocols, particularly within the constraints of free-tier accounts on AWS and Render. 

3. Stabilizing the deployment process, code refactoring for improved efficiency, and implementing continuous integration to enhance our development workflow.
