### ISSUE TITLE
NearByProperty: should list only the same listingStatus

### ISSUE THREAD

**Issue by jieunkxx** [thekimsplustwo/VanCityPropertyPulse#294]
- property: nearby listing should only show the same listingStatus of the property
   - `FOR_SALE` => `FOR_SALE`
- having all kinds of listing status makes the average price odd

#### action item
- our app is only listing `FOR_SALE` status
- if we want to list all the statuses, we need to remove the limit
 
#### screenshots
- current
![Screenshot 2023-08-05 at 3 37 54 PM](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/67996710/eb180a44-32c2-4deb-9f22-238de695d3c8)

**Comment by chohyeonkim** [comment]
@jieunkxx  Some places (especially most of houses) only 'Others' as Nearby Home , (you can double filter houses and see) if we filter out all of them Most of the houses would not have any Nearby homes at all. Instead, since we use separate List for the Bar chart  we can use median price or average price for only (For Sale) - if any exist

![image](https://github.com/thekimsplustwo/VanCityPropertyPulse/assets/104462860/4736a879-4084-422b-8052-adeaa7ffdf65)

**Comment by pukkuKim** [comment]
I've filtered the result w/ the value of `livingStatus` as "FOR_SALE" and created a PR.
We can decide whether we want to apply the change to the app or follow Elly's suggestion 🙂
